#!/bin/bash
echo "Banyg Project Structure Verification"
echo "======================================"
echo ""
echo "Modules:"
./gradlew projects | grep "Project" || echo "Run './gradlew projects' to see modules"
echo ""
echo "Project structure created successfully!"
echo ""
echo "Next steps:"
echo "1. Open project in Android Studio"
echo "2. Sync Gradle"
echo "3. Run: ./gradlew build"
echo "4. Run tests: ./gradlew test"
